Espaço elementar, regra 232 para retículado de N=64, e 20N steps
Conversões para 1 Corretas: 92961
Conversões para 0 Corretas: 0
Conversões para 1 Erradas: 0
Conversões para 0 Erradas: 0
Conversões para Quase 1 Corretas: 156691
Conversões para Quase 0 Corretas: 0
Conversões para Quase 1 Erradas: 0
Conversões para Quase 0 Erradas: 0
Conversões sem solução: 750351

Respondeu corretamente em 9.296% dos casos

Matriz Bidimensional, regra de Tom para retículado de 8x8, e 20*64 steps
Conversões para 1 Corretas: 520218
Conversões para 0 Corretas: 117099
Conversões para 1 Erradas: 0
Conversões para 0 Erradas: 151934
Conversões para 1 Quase Corretas: 0
Conversões para 0 Quase Corretas: 0
Conversões para Quase 1 Erradas: 0
Conversões para Quase 0 Erradas: 0
Conversões sem solução: 210752

Respondeu corretamente em 63.7315% dos casos

Legenda das colunas "Answer":
0: Mais zeros que um
1: Mais uns que zero
2: Metade zeros, metade uns
3: Reticulado não convergiu à zeros nem à uns
4: 92.1875% do reticulado convergiu à zeros
5: 92.1875% do reticulado convergiu à uns


--Agrupando respostas dadas
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 1 AND CORRECTANSWER = 1
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 0 AND CORRECTANSWER = 0
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 1 AND CORRECTANSWER = 0
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 0 AND CORRECTANSWER = 1
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 5 AND CORRECTANSWER = 1
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 4 AND CORRECTANSWER = 0
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 5 AND CORRECTANSWER = 0
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 4 AND CORRECTANSWER = 1
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE ROLE232ANSWER = 3

SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 1 AND CORRECTANSWER = 1
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 0 AND CORRECTANSWER = 0
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 1 AND CORRECTANSWER = 0
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 0 AND CORRECTANSWER = 1
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 5 AND CORRECTANSWER = 1
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 4 AND CORRECTANSWER = 0
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 5 AND CORRECTANSWER = 0
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 4 AND CORRECTANSWER = 1
SELECT COUNT(1) FROM SAMPLES WITH(NOLOCK) WHERE TOMSROLEANSWER = 3
SELECT COUNT(1), TOMSROLEANSWER FROM SAMPLES WITH(NOLOCK) GROUP BY TOMSROLEANSWER 


SELECT * FROM SAMPLES