CREATE PROCEDURE CC_SP_PSGETALL
AS
SELECT * FROM PAIS
RETURN 0


CREATE PROCEDURE CC_SP_PSINSERT 
	@PSNOME VARCHAR(30), 
	@PSSIGLA CHAR(2)
AS
INSERT INTO PAIS (PSNOME, PSSIGLA) VALUES(@PSNOME, @PSSIGLA)
RETURN 0

CREATE PROCEDURE CC_SP_ESINSERT
	@ESPSID INT,
	@ESNOME VARCHAR(30), 
	@ESSIGLA CHAR(2)
AS
INSERT INTO ESTADO (ESPSID, ESNOME, ESSIGLA) VALUES(@ESPSID, @ESNOME, @ESSIGLA)
RETURN 0


CREATE  PROCEDURE CC_SP_ESGETPSID
	@ESPSID INT
AS
SELECT * FROM ESTADO WHERE ESPSID = @ESPSID
RETURN 0


CREATE PROCEDURE CC_SP_CDINSERT
	@CDESID INT,
	@CDNOME VARCHAR(30)
AS
INSERT INTO CIDADE (CDESID, CDNOME) VALUES(@CDESID, @CDNOME)
RETURN 0


CREATE PROCEDURE CC_SP_CDGETESID
	@CDESID INT
AS
SELECT * FROM CIDADE  WHERE CDESID = @CDESID
RETURN 0


CREATE PROCEDURE CC_SP_ENGETID
	@ENID INT
AS
SELECT * FROM ENDERECO
INNER JOIN CIDADE ON CDID = ENCDID
INNER JOIN ESTADO ON ESID = CDESID
INNER JOIN PAIS ON PSID = ESPSID
WHERE
	ENID = @ENID

RETURN 0

CREATE PROCEDURE CC_SP_ENINSERT
	@ENCDID INT,
	@ENRUA VARCHAR(30),
	@ENNUMERO VARCHAR(10),
	@ENCEP CHAR(8),
	@ENCOMPLEMENTO VARCHAR(30)
AS
INSERT INTO ENDERECO 
	(
		ENCDID, 
		ENRUA,
		ENNUMERO,
		ENCEP,
		ENCOMPLEMENTO
	) 
	VALUES
	(
		@ENCDID, 
		@ENRUA,
		@ENNUMERO,
		@ENCEP,
		@ENCOMPLEMENTO
	)
RETURN 0
