CREATE TABLE PAIS
(
PSID INT IDENTITY(1, 1) NOT NULL,
PSNOME VARCHAR(30) NOT NULL,
PSSIGLA CHAR(2) NOT NULL,
CONSTRAINT PK_PSID PRIMARY KEY (PSID),
);


CREATE TABLE ESTADO
(
ESID INT IDENTITY(1, 1) NOT NULL,
ESPSID INT NOT NULL,
ESNOME VARCHAR(30) NOT NULL,
ESSIGLA CHAR(2) NOT NULL,
CONSTRAINT PK_ESID PRIMARY KEY (ESID),
CONSTRAINT FK_ESPSID FOREIGN KEY (ESPSID) REFERENCES PAIS(PSID)
);


CREATE TABLE CIDADE
(
CDID INT IDENTITY(1,1) NOT NULL,
CDESID INT NOT NULL,
CDNOME VARCHAR(30) NOT NULL,
CONSTRAINT PK_CDID PRIMARY KEY (CDID),
CONSTRAINT FK_CDESID FOREIGN KEY (CDESID) REFERENCES ESTADO(ESID)
);

CREATE TABLE ENDERECO
(
ENID INT IDENTITY(1,1) NOT NULL,
ENCDID INT NOT NULL,

ENRUA VARCHAR(30) NOT NULL,
ENNUMERO VARCHAR(10) NOT NULL,
ENCEP CHAR(8) NOT NULL,
ENCOMPLEMENTO VARCHAR(30) NOT NULL,

CONSTRAINT PK_ENID PRIMARY KEY (ENID),
CONSTRAINT FK_ENCDID FOREIGN KEY (ENCDID) REFERENCES CIDADE(CDID)
);

ALTER TABLE ENDERECO ADD CONSTRAINT DF_ENRUA DEFAULT ('') FOR ENRUA
ALTER TABLE ENDERECO ADD CONSTRAINT DF_ENNUMERO DEFAULT ('') FOR ENNUMERO
ALTER TABLE ENDERECO ADD CONSTRAINT DF_ENCEP DEFAULT ('') FOR ENCEP
ALTER TABLE ENDERECO ADD CONSTRAINT DF_ENCOMPLEMENTO DEFAULT ('') FOR ENCOMPLEMENTO

CREATE TABLE GENERO
(
GNID INT IDENTITY(1,1) NOT NULL,
GNGENERO VARCHAR(20) NOT NULL,

CONSTRAINT PK_GNID PRIMARY KEY (GNID),
);

CREATE TABLE USUARIO
(
USID INT IDENTITY(1,1) NOT NULL,
USENID INT NOT NULL,
USEMAIL VARCHAR(25) NOT NULL,
USNICKENAME VARCHAR(15) NOT NULL,
USSENHA VARCHAR(25) NOT NULL,
USNOME VARCHAR(15) NOT NULL,
USSOBRENOME VARCHAR(30) NOT NULL,
USDTNASCIMENTO SMALLDATETIME NOT NULL,
USDESCRICAO VARCHAR(1000) NOT NULL,

CONSTRAINT PK_USID PRIMARY KEY (USID),
CONSTRAINT FK_USENID FOREIGN KEY (USENID) REFERENCES ENDERECO(ENID)
);

ALTER TABLE USUARIO ADD CONSTRAINT DF_USDESCRICAO DEFAULT ('') FOR USDESCRICAO
ALTER TABLE USUARIO ADD CONSTRAINT DF_USSOBRENOME DEFAULT ('') FOR USSOBRENOME
ALTER TABLE USUARIO ADD CONSTRAINT UQ_USEMAIL UNIQUE (USEMAIL)
ALTER TABLE USUARIO ADD CONSTRAINT UQ_USNICKENAME UNIQUE (USNICKENAME)

CREATE TABLE TIPOIMAGEMUS
(
TUID INT IDENTITY(1, 1) NOT NULL,
TUTIPO VARCHAR(10) NOT NULL

CONSTRAINT PK_TUID PRIMARY KEY (TUID)
);

CREATE TABLE IMAGEMUS
(
IUID INT IDENTITY(1, 1) NOT NULL,
IUTUID INT NOT NULL,
IUUSID INT NOT NULL,
IUCAMINHO VARCHAR(50) NOT NULL,

CONSTRAINT PK_IUID PRIMARY KEY (IUID),
CONSTRAINT FK_IUTUID FOREIGN KEY (IUTUID) REFERENCES TIPOIMAGEMUS(TUID),
CONSTRAINT FK_IUUSID FOREIGN KEY (IUUSID) REFERENCES USUARIO(USID)
);