IF EXISTS (SELECT * FROM SYSOBJECTS WHERE TYPE = 'P' AND NAME = 'CA_CREATESAMPLE')
	BEGIN
		PRINT 'DROPPING PROCEDURE CA_CREATESAMPLE'
		DROP  PROCEDURE CA_CREATESAMPLE
	END
GO

PRINT 'CREATING PROCEDURE CA_CREATESAMPLE'
GO

CREATE PROCEDURE CA_CREATESAMPLE
	@STATE BIGINT
AS

/******************************************************************************
**		NOME DO AQUIVO: CA_CREATESAMPLE.SQL
**		NOME DA PROCEDURE: CA_CREATESAMPLE
**
**		DESCRIÇÃO: PROCEDURE RESPONSÁVEL POR INSERIR UM ESTADO INICIAL PARA TESTE
**				   RETORNA 0 SE INSERIR COM SUCESSO, OU 1 CASO O ESTADO JÁ EXISTA
**
**		TEAMPLATE ELABORADO POR: EWERTON DE PAULA DINIZ
**              
**		PROGRAMADOR AUTOR: WILLIAM BARBOSA DOS SANTOS
**		DATA: 29/10/2016
*******************************************************************************
**		HISTÓRICO DE ALTERAÇÕES
*******************************************************************************
**		DATA:		AUTOR:				DESCRIÇÃO:
**
*******************************************************************************/



IF(EXISTS(SELECT TOP 1 1 FROM SAMPLES WHERE INITIALSTATE = @STATE))
	RETURN 1
ELSE
	INSERT INTO SAMPLES (INITIALSTATE, CORRECTANSWER, ROLE232ANSWER, TOMSROLEANSWER) VALUES (@STATE, 99, 99, 99)

RETURN 0

GO