IF EXISTS (SELECT * FROM SYSOBJECTS WHERE TYPE = 'P' AND NAME = 'CA_GETCORRECTPENDENCIES')
	BEGIN
		PRINT 'DROPPING PROCEDURE CA_GETCORRECTPENDENCIES'
		DROP  PROCEDURE CA_GETCORRECTPENDENCIES
	END
GO

PRINT 'CREATING PROCEDURE CA_GETCORRECTPENDENCIES'
GO

CREATE PROCEDURE CA_GETCORRECTPENDENCIES
	@QTD INT,
	@WHATANSWER INT
AS

/******************************************************************************
**		NOME DO AQUIVO: CA_GETCORRECTPENDENCIES.SQL
**		NOME DA PROCEDURE: CA_GETCORRECTPENDENCIES
**
**		DESCRIÇÃO: EXCLUI SAMPLES REPETIDOS
**				   RETORNA A QUANTIDADE DE SAMPLES EXCLUÍDOS
**
**		TEAMPLATE ELABORADO POR: EWERTON DE PAULA DINIZ
**              
**		PROGRAMADOR AUTOR: WILLIAM BARBOSA DOS SANTOS
**		DATA: 29/10/2016
*******************************************************************************
**		HISTÓRICO DE ALTERAÇÕES
*******************************************************************************
**		DATA:		AUTOR:				DESCRIÇÃO:
**
*******************************************************************************/

SET ROWCOUNT @QTD

DECLARE @ID INT

IF(@WHATANSWER = 0)
BEGIN
	SELECT @ID = MIN(ID) FROM SAMPLES WHERE CORRECTANSWER = 99
	UPDATE SAMPLES SET CORRECTANSWER = 98 WHERE CORRECTANSWER = 99
	SELECT * FROM SAMPLES WHERE CORRECTANSWER = 98 AND ID >= @ID
END
ELSE IF(@WHATANSWER = 1)
BEGIN
	SELECT @ID = MIN(ID) FROM SAMPLES WHERE ROLE232ANSWER = 99
	UPDATE SAMPLES SET ROLE232ANSWER = 98 WHERE ROLE232ANSWER = 99
	SELECT * FROM SAMPLES WHERE ROLE232ANSWER = 98 AND ID >= @ID
END
ELSE
BEGIN
	SELECT @ID = MIN(ID) FROM SAMPLES WHERE TOMSROLEANSWER = 99
	UPDATE SAMPLES SET TOMSROLEANSWER = 98 WHERE TOMSROLEANSWER = 99
	SELECT * FROM SAMPLES WHERE TOMSROLEANSWER = 98 AND ID >= @ID
END

SET ROWCOUNT 0

GO