CREATE TABLE SAMPLES
(
	ID INT IDENTITY PRIMARY KEY,
	INITIALSTATE BIGINT NOT NULL,
	CORRECTANSWER BIT NULL,
	ROLE232ANSWER BIT NULL ,
	TOMSROLEANSWER BIT NULL
)


CREATE INDEX SAMPLES_IN_01 ON SAMPLES (INITIALSTATE)
CREATE INDEX SAMPLES_IN_02 ON SAMPLES (CORRECTANSWER)
CREATE INDEX SAMPLES_IN_03 ON SAMPLES (ROLE232ANSWER)
CREATE INDEX SAMPLES_IN_04 ON SAMPLES (TOMSROLEANSWER)